# install-factory-cmd.ps1
#
# Adds a `factory` command to your PowerShell profile so the lifecycle
# commands work from any directory:
#
#   factory start              # start both factories
#   factory start btc-5m       # start only btc-5m
#   factory stop               # stop both
#   factory status             # one-shot table
#   factory monitor            # live dashboard
#   factory resume             # restart any factory whose PID died
#
# The function internally cd's to the project root before invoking npm,
# so you can be in any directory when you run it.
#
# Run this script ONCE:
#
#   powershell -ExecutionPolicy Bypass -File scripts\install-factory-cmd.ps1
#
# After it finishes, open a NEW PowerShell window (or run `. $PROFILE`)
# to pick up the new function. Re-running this script is idempotent —
# it replaces the existing block in place.

$ErrorActionPreference = "Stop"

# 1. Resolve the project root from this script's location (works regardless
#    of where the user invoked the installer from).
$projectRoot = Split-Path -Parent $PSScriptRoot
Write-Host "Project root: $projectRoot"

# 2. PowerShell 5.1 (Windows PowerShell) and PowerShell 7+ (pwsh) use
#    DIFFERENT profile paths. Install into both so `factory` works
#    regardless of which shell you launch. OneDrive Document redirection
#    moves these under OneDrive\Documents\... — discover them via the
#    standard documents folder rather than hard-coding.
$docsDir = [Environment]::GetFolderPath('MyDocuments')
$profileTargets = @(
    (Join-Path $docsDir 'WindowsPowerShell\Microsoft.PowerShell_profile.ps1'),  # PS 5.1
    (Join-Path $docsDir 'PowerShell\Microsoft.PowerShell_profile.ps1')          # PS 7+
)
# Also include the currently-running shell's $PROFILE in case Documents
# isn't redirected the same way.
if ($profileTargets -notcontains $PROFILE) { $profileTargets += $PROFILE }

# 3. The block we will write. Markers let us replace it on subsequent runs.
$startMarker = "# >>> polymarket-factory-cmd >>>"
$endMarker   = "# <<< polymarket-factory-cmd <<<"

$body = @"
$startMarker
# Auto-generated by scripts/install-factory-cmd.ps1 — do not edit by hand.
# Re-run the installer to update.
function factory {
    `$projectRoot = '$projectRoot'
    if (-not (Test-Path (Join-Path `$projectRoot 'package.json'))) {
        Write-Error "factory: project root not found at `$projectRoot — re-run install-factory-cmd.ps1"
        return
    }
    Push-Location `$projectRoot
    try {
        if (`$args.Count -eq 0) {
            npm run factory:status
        } else {
            `$sub = `$args[0]
            `$rest = if (`$args.Count -gt 1) { `$args[1..(`$args.Count - 1)] } else { @() }
            switch (`$sub) {
                'start'     { npm run factory:start -- @rest }
                'stop'      { npm run factory:stop  -- @rest }
                'resume'    { npm run factory:resume }
                'status'    { npm run factory:status }
                'monitor'   { npm run factory:monitor }
                'dashboard' { npm run factory:dashboard }
                'dash'      { npm run factory:dashboard }
                'progress'  { npm run factory:dashboard:once }
                'windows'   { npm run factory:windows -- @rest }
                'popup'     { npm run factory:windows -- @rest }
                default     {
                    Write-Host "factory: unknown subcommand '`$sub'"
                    Write-Host "usage: factory [start|stop|resume|status|monitor|dashboard|progress|windows] [btc-5m|multi]"
                }
            }
        }
    } finally {
        Pop-Location
    }
}
$endMarker
"@

# 4. For each profile path, read existing content, strip any prior factory
#    block, append the new one. Get-Content -Raw on an empty file returns
#    $null; coerce to empty string.
foreach ($profilePath in $profileTargets) {
    if (-not (Test-Path $profilePath)) {
        Write-Host "Creating profile at $profilePath"
        New-Item -ItemType File -Path $profilePath -Force | Out-Null
    }
    $current = ""
    $raw = Get-Content $profilePath -Raw
    if ($null -ne $raw) { $current = $raw }

    if ($current -match "(?s)$([regex]::Escape($startMarker)).*?$([regex]::Escape($endMarker))") {
        $current = [regex]::Replace($current, "(?s)$([regex]::Escape($startMarker)).*?$([regex]::Escape($endMarker))", "")
        Write-Host "  - replacing existing block in $profilePath"
    } else {
        Write-Host "  - adding block to $profilePath"
    }
    $current = $current.TrimEnd() + "`r`n`r`n" + $body + "`r`n"
    Set-Content -Path $profilePath -Value $current -NoNewline
}

Write-Host ""
Write-Host "Installed to both PS 5.1 + PS 7+ profiles."
Write-Host "Open a NEW PowerShell window and try:"
Write-Host "  factory status"
Write-Host "  factory monitor"
Write-Host ""
Write-Host "Or reload right now in your current window:  . `$PROFILE"
